[project]
name = "tactill"
# use dynamic version to avoid sync issues with uv.lock after 'release-please'
dynamic = ["version"]
requires-python = ">=3.14"
dependencies = [
    "httpx2>=2.9",
    "pydantic>=2.13",
]

[dependency-groups]
dev = [
    "mypy==2.3.0",
    "pytest==9.1.1",
    "pydantic-settings==2.14.2",
    "ruff==0.16.1",
    "ty==0.0.68",
]

[tool.ruff]
output-format = "concise"

[tool.ruff.lint]
select = [
    "E", "W", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
    "PL", # Pylint
    "RUF",
    "ANN", # flake8-annotations
]
ignore = [
    "PLR0913", # too-many-arguments
    "PLR0917", # Too many positional arguments (7 > 5)
    "SIM117", # multiple-with-statements
]

[tool.ty.terminal]
output-format = "concise"

[tool.mypy]
strict = true
plugins = ['pydantic.mypy']

[tool.pytest.ini_options]
markers = [
    "skip_on_ci",
]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(name)30s - %(message)s"
