TAX_RATES = [0, 5.5, 10, 20]
CATEGORIES = [
    "ABSINTHE",
    "ACCESSOIRE",
    "ALIMENTATION",
    "ANISÉ",
    "ARMAGNAC",
    "BIB",
    "BIÈRE",
    "BSA",
    "CACHAÇA",
    "CIDRE",
    "COFFRET",
    "COGNAC",
    "EMBALLAGE",
    "FÛT",
    "GIN",
    "LIQUEUR",
    "MADÈRE",
    "MEZCAL",
    "MINI-FÛT",
    "PINEAU",
    "PORTO",
    "RHUM",
    "RHUM ARRANGÉ",
    "VIN",
    "VIN EFFERVESCENT",
    "VIN MUTÉ",
    "VODKA",
    "WHISKY",
    "XÉRÈS",
]
